# Sorting, Counting, Subsetting

## Import libraries

In [2]:
## import libraries
import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [3]:
## import summer data
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")

dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [4]:
## import winter data

dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")

dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [5]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.

dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [6]:
## WINTER
## what exactly do we have: columns, datatypes, etc.

dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

## Subsetting dataframes into smaller, targeted dataframes

When you subset a dataframe, you are filtering down based on selecting specific columns. We want to winnow a large dataset to manageable size by including only relevant columns.

There are two ways of doing this. One simple method is very common (you'll see many people use it), but the other method (also simple) is way more powerful and flexible.

### Method 1 - Pass a list of multiple column headers, it returns dataframe with only those columns
This is like calling a series (```df["Year"]```), but multiple columns:

####  ```df[["Column 1", "Column 2"]]```

In [7]:
## Create a dataframe that for only summer games years and cities

dfs_yr_city = dfs[["Year", "City"]]

dfs_yr_city

        Year            City
0       1896          Athina
1       1896          Athina
2       1896          Athina
3       1896          Athina
4       1896          Athina
...      ...             ...
222547  2016  Rio de Janeiro
222548  2016  Rio de Janeiro
222549  2016  Rio de Janeiro
222550  2016  Rio de Janeiro
222551  2016  Rio de Janeiro

[222552 rows x 2 columns]

## Sorting by single value

```dataframe.sort_values(by="Value 1", ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [8]:
## sort by athlete names A-Z for winter olympics

dfw.sort_values(by="Athlete Name", ascending = True)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
2788,56427,Aage Justesen,M,30.0,NaN,NaN,Denmark,DEN,1948,Sankt Moritz,Speed Skating,Speed Skating Men's 500 metres,NaN
15974,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,Speed Skating Women's 500 metres,NaN
15975,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
3799,49758,Aarne Vin Edward Honkavaara,M,27.0,184.0,81.0,Finland,FIN,1952,Oslo,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
44053,12407,Aaron Blunck,M,17.0,180.0,78.0,United States,USA,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Halfpipe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15622,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
15623,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
8706,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
8705,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
8704,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Downhill,NaN

In [9]:
## sort city z-a

dfw.sort_values(by = "City", ascending = False)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
39561,11951,Ole Einar Bjrndalen,M,36.0,178.0,65.0,Norway,NOR,2010,Vancouver,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,Gold
40747,52463,Marc Iselin,M,29.0,178.0,83.0,Switzerland,SUI,2010,Vancouver,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN
40741,52316,Dmitry Gennadyevich Ipatov,M,25.0,176.0,60.0,Russia,RUS,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40742,52345,"Michael James Grant ""Mike"" Ireland",M,36.0,181.0,79.0,Canada,CAN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
40743,52392,Haley Lyn Irwin,F,21.0,170.0,78.0,Canada,CAN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,75068,Dennis Edward Marineau,M,29.0,172.0,81.0,Canada-2,CAN,1992,Albertville,Bobsleigh,Bobsleigh Men's Two,NaN
22494,74979,Diego Margozzini,M,21.0,182.0,76.0,Chile,CHI,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
22493,74960,Pascal Margerit,M,20.0,180.0,75.0,France,FRA,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
22492,74931,Alexander Marent,M,22.0,168.0,68.0,Austria,AUT,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
21917,53932,Pawe Julian Jaroszek,M,20.0,185.0,82.0,Poland,POL,1992,Albertville,Speed Skating,"Speed Skating Men's 1,500 metres",NaN

## Sorting by multiple values

```dataframe.sort_values(by=["Value 1", "Value 2"], ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [10]:
## Sort by values (City and Year) for winter olympics

dfw_city_year_sort = dfw.sort_values(by = ["City", "Year"], ascending = True)

print(dfw_city_year_sort.tail(100).to_string())

           ID                            Athlete Name Sex   Age  Height  Weight            Team  NOC  Year       City                      Sport                                                 Event   Medal
43573  133769           Roman Yaroslavovych Zakharkiv   M  19.0   174.0    70.0       Ukraine-2  UKR  2010  Vancouver                       Luge                            Luge Mixed (Men)'s Doubles     NaN
43574  133778        Konstantin Mikhaylovich Zakharov   M  24.0   186.0    93.0         Belarus  BLR  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43575  133782             Ruslan Albertovich Zakharov   M  22.0   173.0    72.0          Russia  RUS  2010  Vancouver  Short Track Speed Skating            Short Track Speed Skating Men's 500 metres     NaN
43576  133782             Ruslan Albertovich Zakharov   M  22.0   173.0    72.0          Russia  RUS  2010  Vancouver  Short Track Speed Skating          Short Track Speed Skating Men's 1,000 metres     NaN
43577  133782             Ruslan Albertovich Zakharov   M  22.0   173.0    72.0          Russia  RUS  2010  Vancouver  Short Track Speed Skating          Short Track Speed Skating Men's 1,500 metres     NaN
43578  133805                         Petra Zakouilov   F  31.0   170.0    68.0  Czech Republic  CZE  2010  Vancouver              Alpine Skiing                    Alpine Skiing Women's Giant Slalom     NaN
43579  133805                         Petra Zakouilov   F  31.0   170.0    68.0  Czech Republic  CZE  2010  Vancouver              Alpine Skiing                          Alpine Skiing Women's Slalom     NaN
43580  133809                         Kimiko Zakreski   F  26.0   173.0    66.0          Canada  CAN  2010  Vancouver               Snowboarding            Snowboarding Women's Parallel Giant Slalom     NaN
43581  133812             Igor Valeryevich Zakurdayev   M  23.0   187.0    98.0      Kazakhstan  KAZ  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Downhill     NaN
43582  133812             Igor Valeryevich Zakurdayev   M  23.0   187.0    98.0      Kazakhstan  KAZ  2010  Vancouver              Alpine Skiing                           Alpine Skiing Men's Super G     NaN
43583  133812             Igor Valeryevich Zakurdayev   M  23.0   187.0    98.0      Kazakhstan  KAZ  2010  Vancouver              Alpine Skiing                      Alpine Skiing Men's Giant Slalom     NaN
43584  133812             Igor Valeryevich Zakurdayev   M  23.0   187.0    98.0      Kazakhstan  KAZ  2010  Vancouver              Alpine Skiing                            Alpine Skiing Men's Slalom     NaN
43585  133812             Igor Valeryevich Zakurdayev   M  23.0   187.0    98.0      Kazakhstan  KAZ  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Combined     NaN
43586  133852                           Jake Zamansky   M  28.0   178.0    84.0   United States  USA  2010  Vancouver              Alpine Skiing                      Alpine Skiing Men's Giant Slalom     NaN
43587  133939                           Zang Jialiang   M  22.0   175.0    70.0           China  CHN  2010  Vancouver                    Curling                                 Curling Men's Curling     NaN
43588  133942                          Thomas Zangerl   M  26.0   181.0    81.0         Austria  AUT  2010  Vancouver           Freestyle Skiing                      Freestyle Skiing Men's Ski Cross     NaN
43589  133963                      Costanza Zanoletti   F  29.0   173.0    59.0           Italy  ITA  2010  Vancouver                   Skeleton                             Skeleton Women's Skeleton     NaN
43590  134018                      Alexandra Zaretski   F  22.0   160.0    55.0          Israel  ISR  2010  Vancouver             Figure Skating                      Figure Skating Mixed Ice Dancing     NaN
43591  134019                          Roman Zaretski   M  26.0   180.0    84.0          Israel  ISR  2010  Vancouver             Figure Skating                      Figure Skating Mixed Ice Dancing     NaN
43592  134032               Danis Zinnurovich Zaripov   M  28.0   185.0    84.0          Russia  RUS  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43593  134085             Jinelle Lynn Zaugg-Siergiej   F  23.0   183.0    80.0   United States  USA  2010  Vancouver                 Ice Hockey                         Ice Hockey Women's Ice Hockey  Silver
43594  134101     Tetiana Mykolavna Zavaliy-Antypenko   F  28.0   158.0    52.0         Ukraine  UKR  2010  Vancouver       Cross Country Skiing            Cross Country Skiing Women's 30 kilometres     NaN
43595  134101     Tetiana Mykolavna Zavaliy-Antypenko   F  28.0   158.0    52.0         Ukraine  UKR  2010  Vancouver       Cross Country Skiing          Cross Country Skiing Women's 15 km Skiathlon     NaN
43596  134101     Tetiana Mykolavna Zavaliy-Antypenko   F  28.0   158.0    52.0         Ukraine  UKR  2010  Vancouver       Cross Country Skiing   Cross Country Skiing Women's 4 x 5 kilometres Relay     NaN
43597  134105               Alyona Igorevna Zavarzina   F  20.0   175.0    60.0          Russia  RUS  2010  Vancouver               Snowboarding            Snowboarding Women's Parallel Giant Slalom     NaN
43598  134114                           Maxim Zavozin   M  24.0   179.0    83.0         Hungary  HUN  2010  Vancouver             Figure Skating                      Figure Skating Mixed Ice Dancing     NaN
43599  134118  Olga Viktorovna Zavyalova (Korneyeva-)   F  37.0   166.0    57.0          Russia  RUS  2010  Vancouver       Cross Country Skiing            Cross Country Skiing Women's 10 kilometres     NaN
43600  134118  Olga Viktorovna Zavyalova (Korneyeva-)   F  37.0   166.0    57.0          Russia  RUS  2010  Vancouver       Cross Country Skiing            Cross Country Skiing Women's 30 kilometres     NaN
43601  134118  Olga Viktorovna Zavyalova (Korneyeva-)   F  37.0   166.0    57.0          Russia  RUS  2010  Vancouver       Cross Country Skiing          Cross Country Skiing Women's 15 km Skiathlon     NaN
43602  134118  Olga Viktorovna Zavyalova (Korneyeva-)   F  37.0   166.0    57.0          Russia  RUS  2010  Vancouver       Cross Country Skiing   Cross Country Skiing Women's 4 x 5 kilometres Relay     NaN
43603  134154   Olga Alekseyevna Zaytseva (-Augustin)   F  31.0   168.0    66.0          Russia  RUS  2010  Vancouver                   Biathlon                Biathlon Women's 7.5 kilometres Sprint     NaN
43604  134154   Olga Alekseyevna Zaytseva (-Augustin)   F  31.0   168.0    66.0          Russia  RUS  2010  Vancouver                   Biathlon                Biathlon Women's 10 kilometres Pursuit     NaN
43605  134154   Olga Alekseyevna Zaytseva (-Augustin)   F  31.0   168.0    66.0          Russia  RUS  2010  Vancouver                   Biathlon           Biathlon Women's 12.5 kilometres Mass Start  Silver
43606  134154   Olga Alekseyevna Zaytseva (-Augustin)   F  31.0   168.0    66.0          Russia  RUS  2010  Vancouver                   Biathlon                        Biathlon Women's 15 kilometres     NaN
43607  134154   Olga Alekseyevna Zaytseva (-Augustin)   F  31.0   168.0    66.0          Russia  RUS  2010  Vancouver                   Biathlon               Biathlon Women's 4 x 6 kilometres Relay    Gold
43608  134168                          Micha Zblewski   M  29.0   186.0    95.0          Poland  POL  2010  Vancouver                  Bobsleigh                                  Bobsleigh Men's Four     NaN
43609  134209                          Gary Zebrowski   M  25.0   179.0    76.0          France  FRA  2010  Vancouver               Snowboarding                           Snowboarding Men's Halfpipe     NaN
43610  134219                           Richard Zednk   M  34.0   186.0    87.0        Slovakia  SVK  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43611  134287                           Katrin Zeller   F  30.0   170.0    60.0         Germany  GER  2010  Vancouver       Cross Country Skiing                   Cross Country Skiing Women's Sprint     NaN
43612  134287                           Katrin Zeller   F  30.0   170.0    60.0         Germany  GER  2010  Vancouver       Cross Country Skiing            Cross Country Skiing Women's 30 kilometres     NaN
43613  134287                           Katrin Zeller   F  30.0   170.0    60.0         Germany  GER  2010  Vancouver       Cross Country Skiing          Cross Country Skiing Women's 15 km Skiathlon     NaN
43614  134287                           Katrin Zeller   F  30.0   170.0    60.0         Germany  GER  2010  Vancouver       Cross Country Skiing   Cross Country Skiing Women's 4 x 5 kilometres Relay  Silver
43615  134340                             Zeng Xiaoye   M  18.0   175.0    60.0           China  CHN  2010  Vancouver               Snowboarding                           Snowboarding Men's Halfpipe     NaN
43616  134389                          Kathrin Zettel   F  23.0   167.0    61.0         Austria  AUT  2010  Vancouver              Alpine Skiing                    Alpine Skiing Women's Giant Slalom     NaN
43617  134389                          Kathrin Zettel   F  23.0   167.0    61.0         Austria  AUT  2010  Vancouver              Alpine Skiing                          Alpine Skiing Women's Slalom     NaN
43618  134389                          Kathrin Zettel   F  23.0   167.0    61.0         Austria  AUT  2010  Vancouver              Alpine Skiing                        Alpine Skiing Women's Combined     NaN
43619  134391                  Carl Henrik Zetterberg   M  29.0   183.0    86.0          Sweden  SWE  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43620  134424                               Zhang Ben   F  24.0   170.0    61.0           China  CHN  2010  Vancouver                 Ice Hockey                         Ice Hockey Women's Ice Hockey     NaN
43621  134434                           Zhang Chengye   M  27.0   175.0    71.0           China  CHN  2010  Vancouver                   Biathlon                   Biathlon Men's 10 kilometres Sprint     NaN
43622  134434                           Zhang Chengye   M  27.0   175.0    71.0           China  CHN  2010  Vancouver                   Biathlon                Biathlon Men's 12.5 kilometres Pursuit     NaN
43623  134434                           Zhang Chengye   M  27.0   175.0    71.0           China  CHN  2010  Vancouver                   Biathlon                          Biathlon Men's 20 kilometres     NaN
43624  134439                               Zhang Dan   F  24.0   167.0    48.0         China-3  CHN  2010  Vancouver             Figure Skating                            Figure Skating Mixed Pairs     NaN
43625  134461                               Zhang Hao   M  25.0   181.0    72.0         China-3  CHN  2010  Vancouver             Figure Skating                            Figure Skating Mixed Pairs     NaN
43626  134469                               Zhang Hui   F  21.0   160.0    58.0           China  CHN  2010  Vancouver  Short Track Speed Skating  Short Track Speed Skating Women's 3,000 metres Relay    Gold
43627  134545                            Zhang Shuang   F  23.0   172.0    70.0           China  CHN  2010  Vancouver              Speed Skating                      Speed Skating Women's 500 metres     NaN
43628  134546                            Zhang Shuang   F  22.0   162.0    58.0           China  CHN  2010  Vancouver                 Ice Hockey                         Ice Hockey Women's Ice Hockey     NaN
43629  134627                           Zhang Zhongqi   M  27.0   180.0    80.0           China  CHN  2010  Vancouver              Speed Skating                        Speed Skating Men's 500 metres     NaN
43630  134641                             Zhao Hongbo   M  36.0   177.0    75.0         China-1  CHN  2010  Vancouver             Figure Skating                            Figure Skating Mixed Pairs    Gold
43631  134657                             Zhao Nannan   F  19.0   162.0    53.0           China  CHN  2010  Vancouver  Short Track Speed Skating          Short Track Speed Skating Women's 500 metres     NaN
43632  134710            Aleksandra Viktorova Zhekova   F  22.0   167.0    63.0        Bulgaria  BUL  2010  Vancouver               Snowboarding                     Snowboarding Women's Boardercross     NaN
43633  134744                               Zheng Xun   M  22.0   188.0    75.0           China  CHN  2010  Vancouver             Figure Skating                      Figure Skating Mixed Ice Dancing     NaN
43634  134821                                Zhou Yan   F  27.0   162.0    60.0           China  CHN  2010  Vancouver                    Curling                               Curling Women's Curling  Bronze
43635  134824                               Zhou Yang   F  18.0   165.0    62.0           China  CHN  2010  Vancouver  Short Track Speed Skating          Short Track Speed Skating Women's 500 metres     NaN
43636  134824                               Zhou Yang   F  18.0   165.0    62.0           China  CHN  2010  Vancouver  Short Track Speed Skating        Short Track Speed Skating Women's 1,000 metres     NaN
43637  134824                               Zhou Yang   F  18.0   165.0    62.0           China  CHN  2010  Vancouver  Short Track Speed Skating        Short Track Speed Skating Women's 1,500 metres    Gold
43638  134824                               Zhou Yang   F  18.0   165.0    62.0           China  CHN  2010  Vancouver  Short Track Speed Skating  Short Track Speed Skating Women's 3,000 metres Relay    Gold
43639  134924                            Marek idlick   M  33.0   180.0    85.0  Czech Republic  CZE  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43640  134939                          Miriam Ziegler   F  15.0   154.0    47.0         Austria  AUT  2010  Vancouver             Figure Skating                        Figure Skating Women's Singles     NaN
43641  135066                              Katia Zini   F  28.0   164.0    57.0           Italy  ITA  2010  Vancouver  Short Track Speed Skating        Short Track Speed Skating Women's 1,500 metres     NaN
43642  135066                              Katia Zini   F  28.0   164.0    57.0           Italy  ITA  2010  Vancouver  Short Track Speed Skating  Short Track Speed Skating Women's 3,000 metres Relay     NaN
43643  135083               Sergey Olegovich Zinovyev   M  29.0   178.0    81.0          Russia  RUS  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43644  135163                         Luiza Zotkowska   F  23.0   160.0    52.0          Poland  POL  2010  Vancouver              Speed Skating                    Speed Skating Women's 1,500 metres     NaN
43645  135163                         Luiza Zotkowska   F  23.0   160.0    52.0          Poland  POL  2010  Vancouver              Speed Skating                    Speed Skating Women's 3,000 metres     NaN
43646  135163                         Luiza Zotkowska   F  23.0   160.0    52.0          Poland  POL  2010  Vancouver              Speed Skating           Speed Skating Women's Team Pursuit (6 laps)  Bronze
43647  135166                              Tom Zmoray   M  20.0   187.0    68.0        Slovakia  SVK  2010  Vancouver                Ski Jumping             Ski Jumping Men's Normal Hill, Individual     NaN
43648  135166                              Tom Zmoray   M  20.0   187.0    68.0        Slovakia  SVK  2010  Vancouver                Ski Jumping              Ski Jumping Men's Large Hill, Individual     NaN
43649  135196                           Armin Zggeler   M  36.0   181.0    88.0           Italy  ITA  2010  Vancouver                       Luge                                    Luge Men's Singles  Bronze
43650  135216                       Sabrina Zollinger   F  16.0   162.0    65.0     Switzerland  SUI  2010  Vancouver                 Ice Hockey                         Ice Hockey Women's Ice Hockey     NaN
43651  135263                          Cristian Zorzi   M  37.0   184.0    75.0           Italy  ITA  2010  Vancouver       Cross Country Skiing    Cross Country Skiing Men's 4 x 10 kilometres Relay     NaN
43652  135263                          Cristian Zorzi   M  37.0   184.0    75.0           Italy  ITA  2010  Vancouver       Cross Country Skiing                Cross Country Skiing Men's Team Sprint     NaN
43653  135293                          Natko Zrni-Dim   M  23.0   175.0    80.0         Croatia  CRO  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Downhill     NaN
43654  135293                          Natko Zrni-Dim   M  23.0   175.0    80.0         Croatia  CRO  2010  Vancouver              Alpine Skiing                           Alpine Skiing Men's Super G     NaN
43655  135293                          Natko Zrni-Dim   M  23.0   175.0    80.0         Croatia  CRO  2010  Vancouver              Alpine Skiing                      Alpine Skiing Men's Giant Slalom     NaN
43656  135293                          Natko Zrni-Dim   M  23.0   175.0    80.0         Croatia  CRO  2010  Vancouver              Alpine Skiing                            Alpine Skiing Men's Slalom     NaN
43657  135293                          Natko Zrni-Dim   M  23.0   175.0    80.0         Croatia  CRO  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Combined     NaN
43658  135343              Aleksandr Yuryevich Zubkov   M  35.0   189.0   102.0        Russia-1  RUS  2010  Vancouver                  Bobsleigh                                   Bobsleigh Men's Two  Bronze
43659  135343              Aleksandr Yuryevich Zubkov   M  35.0   189.0   102.0        Russia-2  RUS  2010  Vancouver                  Bobsleigh                                  Bobsleigh Men's Four     NaN
43660  135365              Mats Andr Zuccarello-Aasen   M  22.0   171.0    74.0          Norway  NOR  2010  Vancouver                 Ice Hockey                           Ice Hockey Men's Ice Hockey     NaN
43661  135467                       Silvan Zurbriggen   M  28.0   185.0    94.0     Switzerland  SUI  2010  Vancouver              Alpine Skiing                            Alpine Skiing Men's Slalom     NaN
43662  135467                       Silvan Zurbriggen   M  28.0   185.0    94.0     Switzerland  SUI  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Combined  Bronze
43663  135485                  Stepan Olegovich Zuyev   M  21.0   189.0    90.0          Russia  RUS  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Downhill     NaN
43664  135485                  Stepan Olegovich Zuyev   M  21.0   189.0    90.0          Russia  RUS  2010  Vancouver              Alpine Skiing                           Alpine Skiing Men's Super G     NaN
43665  135485                  Stepan Olegovich Zuyev   M  21.0   189.0    90.0          Russia  RUS  2010  Vancouver              Alpine Skiing                      Alpine Skiing Men's Giant Slalom     NaN
43666  135485                  Stepan Olegovich Zuyev   M  21.0   189.0    90.0          Russia  RUS  2010  Vancouver              Alpine Skiing                            Alpine Skiing Men's Slalom     NaN
43667  135485                  Stepan Olegovich Zuyev   M  21.0   189.0    90.0          Russia  RUS  2010  Vancouver              Alpine Skiing                          Alpine Skiing Men's Combined     NaN

In [11]:
pd.set_option('display.max_rows', 200)

dfw_city_year_sort.tail(100)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
43573,133769,Roman Yaroslavovych Zakharkiv,M,19.0,174.0,70.0,Ukraine-2,UKR,2010,Vancouver,Luge,Luge Mixed (Men)'s Doubles,NaN
43574,133778,Konstantin Mikhaylovich Zakharov,M,24.0,186.0,93.0,Belarus,BLR,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43575,133782,Ruslan Albertovich Zakharov,M,22.0,173.0,72.0,Russia,RUS,2010,Vancouver,Short Track Speed Skating,Short Track Speed Skating Men's 500 metres,NaN
43576,133782,Ruslan Albertovich Zakharov,M,22.0,173.0,72.0,Russia,RUS,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Men's 1,000 metres",NaN
43577,133782,Ruslan Albertovich Zakharov,M,22.0,173.0,72.0,Russia,RUS,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Men's 1,500 metres",NaN
43578,133805,Petra Zakouilov,F,31.0,170.0,68.0,Czech Republic,CZE,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
43579,133805,Petra Zakouilov,F,31.0,170.0,68.0,Czech Republic,CZE,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
43580,133809,Kimiko Zakreski,F,26.0,173.0,66.0,Canada,CAN,2010,Vancouver,Snowboarding,Snowboarding Women's Parallel Giant Slalom,NaN
43581,133812,Igor Valeryevich Zakurdayev,M,23.0,187.0,98.0,Kazakhstan,KAZ,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
43582,133812,Igor Valeryevich Zakurdayev,M,23.0,187.0,98.0,Kazakhstan,KAZ,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Super G,NaN
43583,133812,Igor Valeryevich Zakurdayev,M,23.0,187.0,98.0,Kazakhstan,KAZ,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43584,133812,Igor Valeryevich Zakurdayev,M,23.0,187.0,98.0,Kazakhstan,KAZ,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
43585,133812,Igor Valeryevich Zakurdayev,M,23.0,187.0,98.0,Kazakhstan,KAZ,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Combined,NaN
43586,133852,Jake Zamansky,M,28.0,178.0,84.0,United States,USA,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43587,133939,Zang Jialiang,M,22.0,175.0,70.0,China,CHN,2010,Vancouver,Curling,Curling Men's Curling,NaN
43588,133942,Thomas Zangerl,M,26.0,181.0,81.0,Austria,AUT,2010,Vancouver,Freestyle Skiing,Freestyle Skiing Men's Ski Cross,NaN
43589,133963,Costanza Zanoletti,F,29.0,173.0,59.0,Italy,ITA,2010,Vancouver,Skeleton,Skeleton Women's Skeleton,NaN
43590,134018,Alexandra Zaretski,F,22.0,160.0,55.0,Israel,ISR,2010,Vancouver,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
43591,134019,Roman Zaretski,M,26.0,180.0,84.0,Israel,ISR,2010,Vancouver,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
43592,134032,Danis Zinnurovich Zaripov,M,28.0,185.0,84.0,Russia,RUS,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43593,134085,Jinelle Lynn Zaugg-Siergiej,F,23.0,183.0,80.0,United States,USA,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
43594,134101,Tetiana Mykolavna Zavaliy-Antypenko,F,28.0,158.0,52.0,Ukraine,UKR,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 30 kilometres,NaN
43595,134101,Tetiana Mykolavna Zavaliy-Antypenko,F,28.0,158.0,52.0,Ukraine,UKR,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 15 km Skiathlon,NaN
43596,134101,Tetiana Mykolavna Zavaliy-Antypenko,F,28.0,158.0,52.0,Ukraine,UKR,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 4 x 5 kilometres ...,NaN
43597,134105,Alyona Igorevna Zavarzina,F,20.0,175.0,60.0,Russia,RUS,2010,Vancouver,Snowboarding,Snowboarding Women's Parallel Giant Slalom,NaN
43598,134114,Maxim Zavozin,M,24.0,179.0,83.0,Hungary,HUN,2010,Vancouver,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
43599,134118,Olga Viktorovna Zavyalova (Korneyeva-),F,37.0,166.0,57.0,Russia,RUS,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 10 kilometres,NaN
43600,134118,Olga Viktorovna Zavyalova (Korneyeva-),F,37.0,166.0,57.0,Russia,RUS,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 30 kilometres,NaN
43601,134118,Olga Viktorovna Zavyalova (Korneyeva-),F,37.0,166.0,57.0,Russia,RUS,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 15 km Skiathlon,NaN
43602,134118,Olga Viktorovna Zavyalova (Korneyeva-),F,37.0,166.0,57.0,Russia,RUS,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 4 x 5 kilometres ...,NaN
43603,134154,Olga Alekseyevna Zaytseva (-Augustin),F,31.0,168.0,66.0,Russia,RUS,2010,Vancouver,Biathlon,Biathlon Women's 7.5 kilometres Sprint,NaN
43604,134154,Olga Alekseyevna Zaytseva (-Augustin),F,31.0,168.0,66.0,Russia,RUS,2010,Vancouver,Biathlon,Biathlon Women's 10 kilometres Pursuit,NaN
43605,134154,Olga Alekseyevna Zaytseva (-Augustin),F,31.0,168.0,66.0,Russia,RUS,2010,Vancouver,Biathlon,Biathlon Women's 12.5 kilometres Mass Start,Silver
43606,134154,Olga Alekseyevna Zaytseva (-Augustin),F,31.0,168.0,66.0,Russia,RUS,2010,Vancouver,Biathlon,Biathlon Women's 15 kilometres,NaN
43607,134154,Olga Alekseyevna Zaytseva (-Augustin),F,31.0,168.0,66.0,Russia,RUS,2010,Vancouver,Biathlon,Biathlon Women's 4 x 6 kilometres Relay,Gold
43608,134168,Micha Zblewski,M,29.0,186.0,95.0,Poland,POL,2010,Vancouver,Bobsleigh,Bobsleigh Men's Four,NaN
43609,134209,Gary Zebrowski,M,25.0,179.0,76.0,France,FRA,2010,Vancouver,Snowboarding,Snowboarding Men's Halfpipe,NaN
43610,134219,Richard Zednk,M,34.0,186.0,87.0,Slovakia,SVK,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43611,134287,Katrin Zeller,F,30.0,170.0,60.0,Germany,GER,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's Sprint,NaN
43612,134287,Katrin Zeller,F,30.0,170.0,60.0,Germany,GER,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 30 kilometres,NaN
43613,134287,Katrin Zeller,F,30.0,170.0,60.0,Germany,GER,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 15 km Skiathlon,NaN
43614,134287,Katrin Zeller,F,30.0,170.0,60.0,Germany,GER,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's 4 x 5 kilometres ...,Silver
43615,134340,Zeng Xiaoye,M,18.0,175.0,60.0,China,CHN,2010,Vancouver,Snowboarding,Snowboarding Men's Halfpipe,NaN
43616,134389,Kathrin Zettel,F,23.0,167.0,61.0,Austria,AUT,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
43617,134389,Kathrin Zettel,F,23.0,167.0,61.0,Austria,AUT,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
43618,134389,Kathrin Zettel,F,23.0,167.0,61.0,Austria,AUT,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Combined,NaN
43619,134391,Carl Henrik Zetterberg,M,29.0,183.0,86.0,Sweden,SWE,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43620,134424,Zhang Ben,F,24.0,170.0,61.0,China,CHN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
43621,134434,Zhang Chengye,M,27.0,175.0,71.0,China,CHN,2010,Vancouver,Biathlon,Biathlon Men's 10 kilometres Sprint,NaN
43622,134434,Zhang Chengye,M,27.0,175.0,71.0,China,CHN,2010,Vancouver,Biathlon,Biathlon Men's 12.5 kilometres Pursuit,NaN
43623,134434,Zhang Chengye,M,27.0,175.0,71.0,China,CHN,2010,Vancouver,Biathlon,Biathlon Men's 20 kilometres,NaN
43624,134439,Zhang Dan,F,24.0,167.0,48.0,China-3,CHN,2010,Vancouver,Figure Skating,Figure Skating Mixed Pairs,NaN
43625,134461,Zhang Hao,M,25.0,181.0,72.0,China-3,CHN,2010,Vancouver,Figure Skating,Figure Skating Mixed Pairs,NaN
43626,134469,Zhang Hui,F,21.0,160.0,58.0,China,CHN,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",Gold
43627,134545,Zhang Shuang,F,23.0,172.0,70.0,China,CHN,2010,Vancouver,Speed Skating,Speed Skating Women's 500 metres,NaN
43628,134546,Zhang Shuang,F,22.0,162.0,58.0,China,CHN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
43629,134627,Zhang Zhongqi,M,27.0,180.0,80.0,China,CHN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
43630,134641,Zhao Hongbo,M,36.0,177.0,75.0,China-1,CHN,2010,Vancouver,Figure Skating,Figure Skating Mixed Pairs,Gold
43631,134657,Zhao Nannan,F,19.0,162.0,53.0,China,CHN,2010,Vancouver,Short Track Speed Skating,Short Track Speed Skating Women's 500 metres,NaN
43632,134710,Aleksandra Viktorova Zhekova,F,22.0,167.0,63.0,Bulgaria,BUL,2010,Vancouver,Snowboarding,Snowboarding Women's Boardercross,NaN
43633,134744,Zheng Xun,M,22.0,188.0,75.0,China,CHN,2010,Vancouver,Figure Skating,Figure Skating Mixed Ice Dancing,NaN
43634,134821,Zhou Yan,F,27.0,162.0,60.0,China,CHN,2010,Vancouver,Curling,Curling Women's Curling,Bronze
43635,134824,Zhou Yang,F,18.0,165.0,62.0,China,CHN,2010,Vancouver,Short Track Speed Skating,Short Track Speed Skating Women's 500 metres,NaN
43636,134824,Zhou Yang,F,18.0,165.0,62.0,China,CHN,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 1,000 metres",NaN
43637,134824,Zhou Yang,F,18.0,165.0,62.0,China,CHN,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 1,500 metres",Gold
43638,134824,Zhou Yang,F,18.0,165.0,62.0,China,CHN,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",Gold
43639,134924,Marek idlick,M,33.0,180.0,85.0,Czech Republic,CZE,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43640,134939,Miriam Ziegler,F,15.0,154.0,47.0,Austria,AUT,2010,Vancouver,Figure Skating,Figure Skating Women's Singles,NaN
43641,135066,Katia Zini,F,28.0,164.0,57.0,Italy,ITA,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 1,500 metres",NaN
43642,135066,Katia Zini,F,28.0,164.0,57.0,Italy,ITA,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",NaN
43643,135083,Sergey Olegovich Zinovyev,M,29.0,178.0,81.0,Russia,RUS,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43644,135163,Luiza Zotkowska,F,23.0,160.0,52.0,Poland,POL,2010,Vancouver,Speed Skating,"Speed Skating Women's 1,500 metres",NaN
43645,135163,Luiza Zotkowska,F,23.0,160.0,52.0,Poland,POL,2010,Vancouver,Speed Skating,"Speed Skating Women's 3,000 metres",NaN
43646,135163,Luiza Zotkowska,F,23.0,160.0,52.0,Poland,POL,2010,Vancouver,Speed Skating,Speed Skating Women's Team Pursuit (6 laps),Bronze
43647,135166,Tom Zmoray,M,20.0,187.0,68.0,Slovakia,SVK,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
43648,135166,Tom Zmoray,M,20.0,187.0,68.0,Slovakia,SVK,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
43649,135196,Armin Zggeler,M,36.0,181.0,88.0,Italy,ITA,2010,Vancouver,Luge,Luge Men's Singles,Bronze
43650,135216,Sabrina Zollinger,F,16.0,162.0,65.0,Switzerland,SUI,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
43651,135263,Cristian Zorzi,M,37.0,184.0,75.0,Italy,ITA,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
43652,135263,Cristian Zorzi,M,37.0,184.0,75.0,Italy,ITA,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's Team Sprint,NaN
43653,135293,Natko Zrni-Dim,M,23.0,175.0,80.0,Croatia,CRO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
43654,135293,Natko Zrni-Dim,M,23.0,175.0,80.0,Croatia,CRO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Super G,NaN
43655,135293,Natko Zrni-Dim,M,23.0,175.0,80.0,Croatia,CRO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43656,135293,Natko Zrni-Dim,M,23.0,175.0,80.0,Croatia,CRO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
43657,135293,Natko Zrni-Dim,M,23.0,175.0,80.0,Croatia,CRO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Combined,NaN
43658,135343,Aleksandr Yuryevich Zubkov,M,35.0,189.0,102.0,Russia-1,RUS,2010,Vancouver,Bobsleigh,Bobsleigh Men's Two,Bronze
43659,135343,Aleksandr Yuryevich Zubkov,M,35.0,189.0,102.0,Russia-2,RUS,2010,Vancouver,Bobsleigh,Bobsleigh Men's Four,NaN
43660,135365,Mats Andr Zuccarello-Aasen,M,22.0,171.0,74.0,Norway,NOR,2010,Vancouver,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
43661,135467,Silvan Zurbriggen,M,28.0,185.0,94.0,Switzerland,SUI,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
43662,135467,Silvan Zurbriggen,M,28.0,185.0,94.0,Switzerland,SUI,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Combined,Bronze
43663,135485,Stepan Olegovich Zuyev,M,21.0,189.0,90.0,Russia,RUS,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
43664,135485,Stepan Olegovich Zuyev,M,21.0,189.0,90.0,Russia,RUS,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Super G,NaN
43665,135485,Stepan Olegovich Zuyev,M,21.0,189.0,90.0,Russia,RUS,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43666,135485,Stepan Olegovich Zuyev,M,21.0,189.0,90.0,Russia,RUS,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
43667,135485,Stepan Olegovich Zuyev,M,21.0,189.0,90.0,Russia,RUS,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Combined,NaN
43668,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
43669,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
43670,135496,Veronika Zvaiov,F,21.0,176.0,62.0,Czech Republic,CZE,2010,Vancouver,Biathlon,Biathlon Women's 7.5 kilometres Sprint,NaN
43671,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43672,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN

In [12]:
## sort by year and then city

In [13]:
## sort by city and year but descending for summer games

In [14]:
## you can store into a new df

## Please don't open till instructed

### Should Winter and Summer data remain separate?

### What if we want to know total gold medals for any country?

### But if we combine them, how to we easily distinguish between summer and winter?

### Creating a new column with a default value

In [15]:
## In the summer dataframe, add "Season" column with the value "Summer"

dfs["Season"] = "summer"
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [16]:
## In the winter dataframe, add "Season" column with the value "Winter"

dfw["Season"]="winter"
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [17]:
## are the two column headers identical?
dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
 13  Season        48564 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 5.2 MB

In [18]:
##check summer
dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
 13  Season        222552 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 23.8 MB

In [19]:
## join winter and summer dataframes together into a dataframe called df

df = pd.concat([dfw,dfs], ignore_index = True)
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
271112,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
271113,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
271114,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  str
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 29.0 MB

In [21]:
### confirm that you have the correct number of rows after the join.
### you can scroll up to count the number of entries in dfs and dfw.
### The totals should be equal to the value generated

## Improving memory allocation

If we were working with a massive dataset, we'd want to find ways to improve processing power.

For example, the following columns have only a few values that repeat again and again as strings. This is highly inefficient.

- The "Season" column has "winter" and "summer",
- The "Medal" column only has "gold", "silver" and "bronze",
- "Gender" at this point in the Olympics only has "male" and "female".

One way to improve memory allocation is to take columns with that contain only a few data points and turn them into categories.

In [22]:
## you should see how "Season", "Medal" and "Gender" are all string objects.
## Note that memory usage: 29+ MB

### Convert to single column to category
```df["column_name"].astype("category")```

In [23]:
## convert gender to category
df["Sex"] = df["Sex"].astype("category")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: category(1), float64(3), int64(2), str(8)
memory usage: 27.1 MB

### Convert to multiple columns to category

 ```df[["column_name1", "column_name2]].astype("category")```

In [24]:
## convert medal and season  to category

df[["Medal", "Season"]] = df[["Medal", "Season"]].astype("category")
df.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter

In [25]:
## See what the memory allocation is now using info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   category
 13  Season        271116 non-null  category
dtypes: category(3), float64(3), int64(2), str(6)
memory usage: 23.5 MB

# It should have dropped to 23.5MB.
That's a big descrease for just about 270,000 rows.

This would have an even bigger impact on larger datasets.

# Query to subset

Create smaller datasets with only the information you want

### Create a subset that holds the results from the Sochi Olympics

```df.query("ColumnName == 'some_value'")```

In [26]:
## return df that holds only Sochi data

df.query("City == 'Sochi' ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

### Note the order of the single and double quotes:

If you open with double quotes, the inner quotes have to be single quotes:

```df.query("City == 'Sochi'")```

If you open with single quotes, the inner quotes have to be double quotes:

```df.query('City == "Sochi"')```


Using the same outer and inner quotes will break your code:
</br>
```df.query("City == "Sochi"") ## will break ```

In [56]:
## Store subset into dataframe called sochi_df
sochi_df = df.query("City == 'Sochi' ")
sochi_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

**Syntax for querying multi-word column names:**

```dataframe.query('`column name` comparison_operator value')```

Note the opening and closing tick marks ``` ` ```

In [57]:
#will break

df.query("`Athlete Name` == 'Jeremy Abbott'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
39272,145,Jeremy Abbott,M,24.0,175.0,70.0,United States,USA,2010,Vancouver,Figure Skating,Figure Skating Men's Singles,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
139567,146,Jeremy Abbott,M,19.0,179.0,71.0,Canada,CAN,1976,Montreal,Canoeing,"Canoeing Men's Canadian Doubles, 1,000 metres",NaN,summer

In [58]:
## query to return on french athletes
df.query("`Team` == 'France'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
6,2329,Louis Albert,M,25.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
19,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
20,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
24,10841,Georges Camille Berthet,M,20.0,NaN,NaN,France,FRA,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Bronze,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270385,129003,Marie Wattel,F,19.0,181.0,71.0,France,FRA,2016,Rio de Janeiro,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN,summer
270695,132134,Isabelle Yacoubou-Dehoui,F,30.0,190.0,104.0,France,FRA,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer
270812,133031,Tony Victor James Yoka,M,24.0,200.0,105.0,France,FRA,2016,Rio de Janeiro,Boxing,Boxing Men's Super-Heavyweight,Gold,summer
270894,133577,Grce Zaadi Deuna,F,23.0,171.0,66.0,France,FRA,2016,Rio de Janeiro,Handball,Handball Women's Handball,Silver,summer
270972,134401,Mickal-Meba Zz,M,22.0,175.0,66.0,France,FRA,2016,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,NaN,summer

## Filtering by dates

You'll learn more about date and time in the coming week. For now, please note how the ```Year``` column is a  ```int64``` object and NOT a ```datetime``` object. We can still work with it for our needs.

In [30]:
## GET INFO

In [59]:
## Find all the 1900 competitions
df.query("Year == 1900")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48944,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,summer
48945,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,summer
48946,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,summer
48947,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,summer
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50875,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze,summer
50876,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN,summer
50877,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN,summer
50878,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN,summer
50879,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold,summer

In [60]:
### return all the competitions between 1920 and 1950 (inclusive)

df.query("1940 <= Year <= 1960 ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
2289,665,Gilbert Achard-Picard,M,29.0,NaN,NaN,France-2,FRA,1948,Sankt Moritz,Bobsleigh,Bobsleigh Men's Four,NaN,winter
2290,810,Bridget Shirley Adams (-Bengough),F,19.0,NaN,NaN,Great Britain,GBR,1948,Sankt Moritz,Figure Skating,Figure Skating Women's Singles,NaN,winter
2291,1508,Enrico Airoldi,M,24.0,NaN,NaN,Italy-2,ITA,1948,Sankt Moritz,Bobsleigh,Bobsleigh Men's Four,NaN,winter
2292,1509,Remo Airoldi,M,26.0,NaN,NaN,Italy-2,ITA,1948,Sankt Moritz,Bobsleigh,Bobsleigh Men's Four,NaN,winter
2293,2876,"Theodor ""Theo"" Allenbach",M,23.0,NaN,NaN,Switzerland,SUI,1948,Sankt Moritz,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112963,135493,Edward uawnik,M,27.0,165.0,73.0,Poland,POL,1960,Roma,Wrestling,"Wrestling Men's Welterweight, Greco-Roman",NaN,summer
112964,135524,"Nicolaus ""Nic"" Zwetnow",M,31.0,181.0,70.0,Norway,NOR,1960,Roma,Shooting,"Shooting Men's Rapid-Fire Pistol, 25 metres",NaN,summer
112965,135532,"Edward ""Eddie"" Zwier",M,26.0,176.0,75.0,Netherlands,NED,1960,Roma,Hockey,Hockey Men's Hockey,NaN,summer
112966,135533,"Petronella Veronica Maria ""Nel"" Zwier",F,23.0,174.0,70.0,Netherlands,NED,1960,Roma,Athletics,Athletics Women's High Jump,NaN,summer
112967,135553,Galina Ivanovna Zybina (-Fyodorova),F,29.0,168.0,80.0,Soviet Union,URS,1960,Roma,Athletics,Athletics Women's Shot Put,NaN,summer

In [61]:
## Were there any games in 1950
df.query("Year == 1950")

Empty DataFrame
Columns: [ID, Athlete Name, Sex, Age, Height, Weight, Team, NOC, Year, City, Sport, Event, Medal, Season]
Index: []

In [62]:
## return only Tennis competitions between 1920 and 1950 (inclusive)
df.query('Sport == "Tennis" and 1920 <= Year <= 1950')

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
61094,2302,Pierre Henri Maurice Albarran,M,26.0,NaN,NaN,France-3,FRA,1920,Antwerpen,Tennis,Tennis Men's Doubles,Bronze,summer
61115,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61116,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer
61117,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61118,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70549,134322,Ladislav emla,M,36.0,NaN,NaN,Czechoslovakia,TCH,1924,Paris,Tennis,Tennis Men's Singles,NaN,summer
70550,134322,Ladislav emla,M,36.0,NaN,NaN,Czechoslovakia-2,TCH,1924,Paris,Tennis,Tennis Men's Doubles,NaN,summer
70551,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Men's Singles,NaN,summer
70552,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Mixed Doubles,NaN,summer
70553,134376,Avgoustos Zerlentis,M,37.0,NaN,NaN,Greece,GRE,1924,Paris,Tennis,Tennis Men's Doubles,NaN,summer

In [63]:
## return only Women's Tennis competitions results
## between 1996 and 2018 inclusive
df.query('Sport == "Tennis" and Sex == "F" and 1996 <= Year <= 2018')

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
190340,4723,Sabine Appelmans (-Haubourdin),F,24.0,169.0,60.0,Belgium,BEL,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer
190341,4723,Sabine Appelmans (-Haubourdin),F,24.0,169.0,60.0,Belgium,BEL,1996,Atlanta,Tennis,Tennis Women's Doubles,NaN,summer
190611,7620,Olga Vladimirovna Barabanshchikova,F,16.0,176.0,60.0,Belarus,BLR,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer
190612,7620,Olga Vladimirovna Barabanshchikova,F,16.0,176.0,60.0,Belarus,BLR,1996,Atlanta,Tennis,Tennis Women's Doubles,NaN,summer
190699,8522,"Nani Rahayu ""Yayuk"" Basuki-Suharyadi",F,25.0,165.0,55.0,Indonesia,INA,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270690,132098,Xu Yifan,F,27.0,165.0,60.0,China-2,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer
271007,134544,Zhang Shuai,F,27.0,177.0,66.0,China,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Singles,NaN,summer
271008,134544,Zhang Shuai,F,27.0,177.0,66.0,China-1,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer
271039,134739,Zheng Saisai,F,22.0,170.0,62.0,China,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Singles,NaN,summer
271040,134739,Zheng Saisai,F,22.0,170.0,62.0,China-2,CHN,2016,Rio de Janeiro,Tennis,Tennis Women's Doubles,NaN,summer

In [64]:
## volleyball or rowing for only Male
df.query('Sex == "M" and (Sport == "Volleyball" or Sport == "Rowing")')

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
48963,3476,Max Heinrich Ammermann,M,21.0,NaN,NaN,Favorite Hammonia-3,GER,1900,Paris,Rowing,Rowing Men's Coxed Fours,Bronze,summer
48975,4343,Angot,M,NaN,NaN,NaN,Club Nautique de Dieppe-5,FRA,1900,Paris,Rowing,Rowing Men's Coxed Fours,NaN,summer
48980,5538,St George Ashe,M,28.0,NaN,NaN,Great Britain,GBR,1900,Paris,Rowing,Rowing Men's Single Sculls,Bronze,summer
49005,8065,Hermann Joseph Barrelet,M,20.0,NaN,NaN,France,FRA,1900,Paris,Rowing,Rowing Men's Single Sculls,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270943,134057,Anton Sergeyevich Zarutsky,M,30.0,195.0,94.0,Russia,RUS,2016,Rio de Janeiro,Rowing,Rowing Men's Coxless Fours,NaN,summer
270946,134081,Pawe Zatorski,M,26.0,184.0,73.0,Poland,POL,2016,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,NaN,summer
270952,134145,Ivan Zaytsev,M,27.0,204.0,100.0,Italy,ITA,2016,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,Silver,summer
271023,134647,Zhao Jingbin,M,26.0,185.0,72.0,China,CHN,2016,Rio de Janeiro,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,summer
271072,134970,Mirosaw Zitarski,M,22.0,190.0,90.0,Poland,POL,2016,Rio de Janeiro,Rowing,Rowing Men's Quadruple Sculls,NaN,summer

## What year was women's boxing introduced to the olympics?

In [37]:
## find all the names of sports first just to confirm boxing
## does not appear in different names
## how is boxing listed?

In [65]:
##step 1 -- get all the unique sports and see how boxing is labeled
df["Sport"].unique()

<StringArray>
[               'Ice Hockey',           'Nordic Combined',
               'Ski Jumping',      'Cross Country Skiing',
                   'Curling',                 'Bobsleigh',
       'Military Ski Patrol',            'Figure Skating',
             'Speed Skating',                  'Alpinism',
                  'Skeleton',             'Alpine Skiing',
                  'Biathlon',                      'Luge',
          'Freestyle Skiing', 'Short Track Speed Skating',
              'Snowboarding',                    'Tennis',
                 'Athletics',                  'Swimming',
                'Gymnastics',                  'Shooting',
                   'Cycling',                   'Fencing',
             'Weightlifting',                 'Wrestling',
                'Tug-Of-War',                      'Golf',
                    'Rowing',                     'Rugby',
                   'Sailing',                  'Football',
                   'Cricket',                'Water Polo',
             'Equestrianism',                   'Croquet',
                   'Archery',                      'Polo',
             'Basque Pelota',                  'Lacrosse',
                    'Boxing',                    'Diving',
                     'Roque',                    'Hockey',
                  'Racquets',              'Motorboating',
              'Jeu De Paume',          'Art Competitions',
         'Modern Pentathlon',                'Basketball',
                  'Handball',                  'Canoeing',
               'Aeronautics',                'Volleyball',
                      'Judo',       'Rhythmic Gymnastics',
     'Synchronized Swimming',              'Table Tennis',
                 'Badminton',                  'Baseball',
          'Beach Volleyball',                  'Softball',
                 'Taekwondo',                 'Triathlon',
              'Trampolining',              'Rugby Sevens']
Length: 66, dtype: str

In [67]:
##step 2 -- query for boxing
df.query('Sport == "Boxing"')

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
50936,10464,"Samuel ""Sam"" Berger",M,19.0,188.0,82.0,United States,USA,1904,St. Louis,Boxing,Boxing Men's Heavyweight,Gold,summer
50971,13003,James Bollinger,M,NaN,NaN,NaN,United States,USA,1904,St. Louis,Boxing,Boxing Men's Lightweight,NaN,summer
51002,16612,Miles J. Burke,M,19.0,160.0,49.0,United States,USA,1904,St. Louis,Boxing,Boxing Men's Flyweight,Silver,summer
51182,35435,George V. Finnegan,M,NaN,NaN,47.0,United States,USA,1904,St. Louis,Boxing,Boxing Men's Flyweight,Gold,summer
51183,35435,George V. Finnegan,M,NaN,NaN,47.0,United States,USA,1904,St. Louis,Boxing,Boxing Men's Bantamweight,Silver,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270975,134412,Birzhan Zhakypovich Zhakypov,M,32.0,167.0,48.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Boxing,Boxing Men's Light-Flyweight,NaN,summer
270987,134476,Zhang Jiawei,M,27.0,172.0,56.0,China,CHN,2016,Rio de Janeiro,Boxing,Boxing Men's Bantamweight,NaN,summer
271027,134656,Zhao Minggang,M,28.0,185.0,75.0,China,CHN,2016,Rio de Janeiro,Boxing,Boxing Men's Middleweight,NaN,summer
271066,134903,Ablaykhan Kayratovich Zhusupov,M,19.0,175.0,64.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Boxing,Boxing Men's Light-Welterweight,NaN,summer
271082,135205,Shakhobiddin Shokirovich Zoirov,M,23.0,169.0,52.0,Uzbekistan,UZB,2016,Rio de Janeiro,Boxing,Boxing Men's Flyweight,Gold,summer

### When did boxing first appear as a sport in which women competed at the olympics?

In [68]:
## query for boxing and women
## store in new df
womens_boxing = df.query('Sport == "Boxing" and Sex == "F"')
womens_boxing

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
244598,832,Nicola Virginia Adams,F,29.0,164.0,51.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Flyweight,Gold,summer
244901,4004,Elizabeth Adhiambo Andiego,F,25.0,172.0,NaN,Kenya,KEN,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
244966,4859,Adriana dos Santos Arajo,F,30.0,167.0,60.0,Brazil,BRA,2012,London,Boxing,Boxing Women's Lightweight,Bronze,summer
246510,21147,Mavzuna Chorieva,F,19.0,160.0,60.0,Tajikistan,TJK,2012,London,Boxing,Boxing Women's Lightweight,Bronze,summer
247253,29367,Dong Cheng,F,25.0,177.0,60.0,China,CHN,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
247629,33192,Marlen Esparza Puentes,F,22.0,160.0,51.0,United States,USA,2012,London,Boxing,Boxing Women's Flyweight,Bronze,summer
247761,34486,Roseli Amaral Feitosa,F,23.0,173.0,79.0,Brazil,BRA,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
247800,34769,Siona Fernandes,F,29.0,163.0,NaN,New Zealand,NZL,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
247882,35549,Naomi-Lee Fischer-Rasmussen,F,28.0,176.0,NaN,Australia,AUS,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
249810,55594,Natasha Paula Jonas,F,28.0,172.0,60.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
249842,56014,Rim Jouini,F,31.0,170.0,NaN,Tunisia,TUN,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
250100,59220,Saida Uralovna Khasenova,F,25.0,169.0,NaN,Kazakhstan,KAZ,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
250193,59968,Kim Hye-Song,F,27.0,163.0,51.0,North Korea,PRK,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
250447,62303,Mangte Chungneijang Mary Kom,F,29.0,158.0,51.0,India,IND,2012,London,Boxing,Boxing Women's Flyweight,Bronze,summer
250753,65703,Mihaela Lctu,F,30.0,167.0,NaN,Romania,ROU,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
250857,67112,Anna Rosalie Eleonora Laurell-Nash,F,32.0,184.0,75.0,Sweden,SWE,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
251080,69416,Li Jinzi,F,22.0,176.0,75.0,China,CHN,2012,London,Boxing,Boxing Women's Middleweight,Bronze,summer
251490,73421,Karlha Francesca Magliocco,F,26.0,157.0,NaN,Venezuela,VEN,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
251675,75428,Savannah Rose Dee Marshall,F,21.0,181.0,75.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
251762,76497,Erica dos Santos Matos,F,29.0,162.0,51.0,Brazil,BRA,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
252033,79355,Karolina Michalczuk,F,32.0,164.0,51.0,Poland,POL,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
252877,87919,Sofya Albertovna Ochigava,F,25.0,170.0,60.0,Russia,RUS,2012,London,Boxing,Boxing Women's Lightweight,Silver,summer
252896,88189,Edith Ogoke,F,21.0,NaN,75.0,Nigeria,NGR,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
253072,90065,Mahjouba Oubtil,F,29.0,NaN,60.0,Morocco,MAR,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
253469,94145,Stoyka Zhelyazkova Petrova,F,26.0,163.0,51.0,Bulgaria,BUL,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
253752,97059,Alexis Pritchard,F,28.0,178.0,NaN,New Zealand,NZL,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
253882,98330,Maroua Rahali,F,24.0,168.0,NaN,Tunisia,TUN,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
254016,99913,Ren Cancan,F,24.0,167.0,51.0,China,CHN,2012,London,Boxing,Boxing Women's Flyweight,Silver,summer
254563,106220,Yelena Vladimirovna Savelyeva,F,28.0,168.0,51.0,Russia,RUS,2012,London,Boxing,Boxing Women's Flyweight,NaN,summer
254892,109724,Claressa Maria Shields,F,17.0,175.0,75.0,United States,USA,2012,London,Boxing,Boxing Women's Middleweight,Gold,summer
255281,113783,Mary Spencer,F,27.0,180.0,73.0,Canada,CAN,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
255782,118917,"Kathleen ""Katie"" Taylor",F,26.0,165.0,60.0,Ireland,IRL,2012,London,Boxing,Boxing Women's Lightweight,Gold,summer
256005,121172,Nadezhda Viktorovna Torlopova,F,33.0,175.0,75.0,Russia,RUS,2012,London,Boxing,Boxing Women's Middleweight,Silver,summer
256223,123331,"Quanita ""Queen"" Underwood",F,28.0,165.0,60.0,United States,USA,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer
256573,126863,Yelena Vstropova,F,23.0,174.0,NaN,Azerbaijan,AZE,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
256607,127225,Marina Ivanovna Volnova,F,22.0,170.0,NaN,Kazakhstan,KAZ,2012,London,Boxing,Boxing Women's Middleweight,Bronze,summer
257541,832,Nicola Virginia Adams,F,33.0,164.0,51.0,Great Britain,GBR,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,Gold,summer
257741,2500,Yana Ivanovna Alekseevna,F,28.0,169.0,60.0,Azerbaijan,AZE,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
257985,4859,Adriana dos Santos Arajo,F,34.0,167.0,60.0,Brazil,BRA,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
258254,7471,Andreia Bandeira,F,29.0,169.0,75.0,Brazil,BRA,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
258492,9823,Anastasiya Yevgenyevna Belyakova,F,23.0,173.0,60.0,Russia,RUS,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,Bronze,summer
259134,16285,Mandy Marie Brigitte Bujold,F,29.0,160.0,51.0,Canada,CAN,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
259193,17072,Atheyna Bylon,F,27.0,175.0,75.0,Panama,PAN,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
259548,20246,Chen Nien-Chin,F,19.0,169.0,75.0,Chinese Taipei,TPE,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
259615,20692,Jennifer Dugwen Chieng,F,30.0,161.0,60.0,Federated States of Micronesia,FSM,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
260915,33584,Zohra Ez Zahraoui,F,32.0,165.0,51.0,Morocco,MAR,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
261163,36182,Nouchka Fontijn,F,28.0,180.0,75.0,Netherlands,NED,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,Silver,summer
261179,36377,Ariane Fortin,F,31.0,180.0,75.0,Canada,CAN,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
263562,61647,Tetiana Volodymyrivna Kob,F,28.0,161.0,51.0,Ukraine,UKR,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
263948,65726,Hasnaa Lachgar,F,26.0,164.0,60.0,Morocco,MAR,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
264018,66595,Peamwilai Laopeam,F,32.0,163.0,51.0,Thailand,THA,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
264064,67112,Anna Rosalie Eleonora Laurell-Nash,F,36.0,184.0,75.0,Sweden,SWE,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
264287,69466,Li Qian,F,26.0,180.0,75.0,China,CHN,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,Bronze,summer
264859,74900,Khadija Al-Mardi,F,25.0,183.0,75.0,Morocco,MAR,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
264909,75428,Savannah Rose Dee Marshall,F,25.0,181.0,75.0,Great Britain,GBR,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
265070,76993,Mikaela Joslin Mayer,F,26.0,175.0,60.0,United States,USA,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
265086,77209,Judith Mbougnade,F,18.0,150.0,51.0,Central African Republic,CAF,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
265425,80304,Yodgoroy Mirzayeva,F,20.0,160.0,51.0,Uzbekistan,UZB,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
265654,82474,Estelle Mossely,F,23.0,168.0,60.0,France,FRA,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,Gold,summer
266454,90133,Sarah Ourahmoune,F,34.0,158.0,51.0,France,FRA,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,Silver,summer
266842,94144,Stanimira Petrova,F,25.0,170.0,51.0,Bulgaria,BUL,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
267093,96466,Mira Potkonen,F,35.0,165.0,60.0,Finland,FIN,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,Bronze,summer
267451,99913,Ren Cancan,F,28.0,167.0,51.0,China,CHN,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,Bronze,summer
268330,109169,Dariga Shakimova,F,27.0,172.0,75.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,Bronze,summer
268378,109487,Zhayna Shekerbekova,F,26.0,155.0,51.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,NaN,summer
268407,109724,Claressa Maria Shields,F,21.0,175.0,75.0,United States,USA,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,Gold,summer
269287,118917,"Kathleen ""Katie"" Taylor",F,30.0,165.0,60.0,Ireland,IRL,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
269356,119382,Irma Testa,F,18.0,174.0,60.0,Italy,ITA,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
269849,123925,Ingrit Lorena Valencia Victoria,F,27.0,160.0,50.0,Colombia,COL,2016,Rio de Janeiro,Boxing,Boxing Women's Flyweight,Bronze,summer
270387,129023,Shelley Marie Watts,F,28.0,164.0,60.0,Australia,AUS,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,NaN,summer
270708,132232,Yaroslava Ivanovna Yakushina,F,23.0,170.0,75.0,Russia,RUS,2016,Rio de Janeiro,Boxing,Boxing Women's Middleweight,NaN,summer
270809,132989,Yin Junhua,F,25.0,167.0,60.0,China,CHN,2016,Rio de Janeiro,Boxing,Boxing Women's Lightweight,Silver,summer

In [69]:
##find the smallest year
womens_boxing["Year"].min()

np.int64(2012)

### How many values in a column?

## Counting

- The ```sum``` adds up all the values in a dataset, to give you the total amount.

- The ```count``` tells you how many items of particular values exist in a dataset. It doesn't care about the values themselves, just the number of entries.

We use the ```.value_counts()``` method:

```df_name["column_name"].value_counts()```

### Summer v. Winter

How many athletes participated in the summer games v. the winter games?

In [74]:
## total number of athletes
df["Athlete Name"].value_counts()

Athlete Name
Robert Tait McKenzie        58
Heikki Ilmari Savolainen    39
Joseph "Josy" Stoffel       38
Ioannis Theofilakis         36
Takashi Ono                 33
                            ..
Stipe uni                    1
Vaida sinait                 1
Henrikas ustautas            1
Martin Zwicker               1
Olga Igorevna Zyuzkova       1
Name: count, Length: 134732, dtype: int64

In [75]:
##There are duplicates. Let's see how many entries are in summer vs. winter games
df["Season"].value_counts()

Season
summer    222552
winter     48564
Name: count, dtype: int64

In [79]:
##each row represents an athlete, so that gives us a sense of participation in each season.
##but some athletes appear more than once
## drop the duplicates 

unique_athletes = df.drop_duplicates(subset=["ID", "Season"])
unique_athletes

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
6,2329,Louis Albert,M,25.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271103,135431,Stipe uni,M,25.0,193.0,134.0,Croatia,CRO,2016,Rio de Janeiro,Athletics,Athletics Men's Shot Put,NaN,summer
271105,135477,Vaida sinait,F,28.0,167.0,50.0,Lithuania,LTU,2016,Rio de Janeiro,Athletics,Athletics Women's Marathon,NaN,summer
271106,135478,Henrikas ustautas,M,22.0,192.0,96.0,Lithuania,LTU,2016,Rio de Janeiro,Canoeing,"Canoeing Men's Canadian Singles, 200 metres",NaN,summer
271110,135525,Martin Zwicker,M,29.0,175.0,64.0,Germany,GER,2016,Rio de Janeiro,Hockey,Hockey Men's Hockey,Bronze,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [81]:
##now use .value_counts on your new df
unique_athletes["Season"].value_counts()

Season
summer    116776
winter     18958
Name: count, dtype: int64

### ```value_counts()``` parameter

By default, it is ```.value_counts(normalize = False)```

This gives you want we calculated above

But ```.value_counts(normalize = True)``` returns  proportions (fractions of the total).

In [40]:
## get as proportion

In [41]:
## convert to you want it as a percentage

In [42]:
## subset data to hold only medals

In [43]:
## what is the total medal count for winter v. summer?

# DRY

Do not repeat yourself

In [44]:
##get list of uniques

In [45]:
# target_medals = ["Gold", "Silver", "Bronze"]

In [46]:
## get head

In [47]:
## call winners

In [48]:
## what is the total medal count for winter v. summer?

## How many medals were handed out at each olympics between 1896 and 2014?

Show the result from highest to lowest.

In [82]:
## We'll need to filter for just the medal winner. 

medals_only = df.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze'")
medals_only

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271064,134857,Zhu Ting,F,21.0,198.0,78.0,China,CHN,2016,Rio de Janeiro,Volleyball,Volleyball Women's Volleyball,Gold,summer
271079,135132,Bojana ivkovi,F,28.0,186.0,72.0,Serbia,SRB,2016,Rio de Janeiro,Volleyball,Volleyball Women's Volleyball,Silver,summer
271082,135205,Shakhobiddin Shokirovich Zoirov,M,23.0,169.0,52.0,Uzbekistan,UZB,2016,Rio de Janeiro,Boxing,Boxing Men's Flyweight,Gold,summer
271087,135245,Milenko Zori,M,27.0,179.0,73.0,Serbia,SRB,2016,Rio de Janeiro,Canoeing,"Canoeing Men's Kayak Doubles, 1,000 metres",Silver,summer
271110,135525,Martin Zwicker,M,29.0,175.0,64.0,Germany,GER,2016,Rio de Janeiro,Hockey,Hockey Men's Hockey,Bronze,summer

In [83]:
## audit result: do we really only have medals

medals_only["Medal"].unique()

['Silver', 'Bronze', 'Gold']
Categories (3, str): ['Bronze', 'Gold', 'Silver']

In [92]:
## how many medals were handed out at each olympics each
## year from as recent as possible down to 1896.
##filter years

medals_only = medals_only.query("1896 <= Year <= 2014")
medals_only

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257391,135269,Zou Kai,M,24.0,158.0,55.0,China,CHN,2012,London,Gymnastics,Gymnastics Men's Team All-Around,Gold,summer
257392,135269,Zou Kai,M,24.0,158.0,55.0,China,CHN,2012,London,Gymnastics,Gymnastics Men's Floor Exercise,Gold,summer
257393,135269,Zou Kai,M,24.0,158.0,55.0,China,CHN,2012,London,Gymnastics,Gymnastics Men's Horizontal Bar,Bronze,summer
257395,135270,Zou Shiming,M,31.0,165.0,49.0,China,CHN,2012,London,Boxing,Boxing Men's Light-Flyweight,Gold,summer
257418,135489,Anastasiya Valeryevna Zuyeva-Fesikova,F,22.0,182.0,71.0,Russia,RUS,2012,London,Swimming,Swimming Women's 200 metres Backstroke,Silver,summer

In [93]:
##count medals by year
medals_only["Year"].value_counts()

Year
2008    2048
1992    2030
2000    2004
2004    2001
2012    1941
1988    1845
1996    1842
1984    1698
1980    1602
1976    1531
1972    1414
1920    1308
1968    1256
1964    1215
1960    1058
1956    1043
1952    1033
1936    1025
1948     987
1924     962
1912     941
1908     831
1928     823
1932     739
1900     604
2014     597
2006     526
2010     520
1904     486
2002     478
1906     458
1998     440
1994     331
1896     143
Name: count, dtype: int64

In [ ]:
##OBSERVATION -- why are the medal counts so high?
##answer --> each line here is an athlete --> team sports, each athlete gets a medal

In [94]:
## top 10 count of gold medals by country
gold_only = df.query("Medal == 'Gold'")

In [95]:
## count of gold medals by country by percent
## only gold winner df
##We filter for gold medals, then count how many each country has.
gold_only["NOC"].value_counts().head(10)

NOC
USA    2638
URS    1082
GER     745
GBR     678
ITA     575
FRA     501
SWE     479
CAN     463
HUN     432
GDR     397
Name: count, dtype: int64

In [98]:
## as percent
##count by country
gold_counts = gold_only["NOC"].value_counts()

In [100]:
##convert to percent
gold_percent = gold_counts / gold_counts.sum() * 100
gold_percent

##We count gold medals by country
##then divide by the total to get each country’s share

NOC
USA    19.727789
URS     8.091535
GER     5.571343
GBR     5.070296
ITA     4.300030
FRA     3.746635
SWE     3.582112
CAN     3.462459
HUN     3.230631
GDR     2.968890
RUS     2.916542
NOR     2.826802
CHN     2.617410
AUS     2.602453
NED     2.146276
JPN     1.847143
KOR     1.652707
FIN     1.480706
DEN     1.338618
SUI     1.308705
CUB     1.226443
ROU     1.204008
FRG     1.189052
IND     1.032007
YUG     0.972181
EUN     0.949746
POL     0.874963
ESP     0.822614
BRA     0.815136
AUT     0.807658
BEL     0.732875
ARG     0.680526
NZL     0.673048
TCH     0.605743
GRE     0.463655
CRO     0.433742
BUL     0.403829
UKR     0.351481
CZE     0.314089
PAK     0.314089
TUR     0.299133
JAM     0.284176
KEN     0.254263
RSA     0.239306
URU     0.231828
MEX     0.224349
BLR     0.179480
NGR     0.172001
ETH     0.164523
KAZ     0.149566
ANZ     0.149566
CMR     0.149566
IRI     0.134610
ZIM     0.127131
PRK     0.119653
SVK     0.112175
SRB     0.112175
BAH     0.104696
EST     0.097218
FIJ     0.097218
SCG     0.089740
INA     0.082261
UZB     0.074783
IRL     0.067305
THA     0.067305
SLO     0.059827
GEO     0.059827
EGY     0.052348
TTO     0.052348
AZE     0.052348
MAR     0.044870
LTU     0.044870
ALG     0.037392
COL     0.037392
LUX     0.029913
POR     0.029913
TUN     0.022435
LAT     0.022435
TPE     0.022435
CHI     0.022435
DOM     0.022435
LIE     0.014957
VEN     0.014957
UGA     0.014957
ARM     0.014957
MGL     0.014957
NEP     0.007478
HAI     0.007478
PER     0.007478
SUR     0.007478
HKG     0.007478
BDI     0.007478
ECU     0.007478
CRC     0.007478
SYR     0.007478
MOZ     0.007478
UAE     0.007478
ISR     0.007478
PAN     0.007478
GRN     0.007478
JOR     0.007478
IOA     0.007478
CIV     0.007478
VIE     0.007478
BRN     0.007478
KOS     0.007478
TJK     0.007478
PUR     0.007478
SGP     0.007478
Name: count, dtype: float64

In [102]:
## how many times did Russia win the gold?

russia_gold = df.query("NOC == 'RUS' and Medal == 'Gold'")
russia_gold

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
24187,8967,Svetlana Valeryevna Bazhanova,F,21.0,175.0,70.0,Russia,RUS,1994,Lillehammer,Speed Skating,"Speed Skating Women's 3,000 metres",Gold,winter
24468,20410,Sergey Vladimirovich Chepikov,M,27.0,182.0,75.0,Russia,RUS,1994,Lillehammer,Biathlon,Biathlon Men's 10 kilometres Sprint,Gold,winter
24848,39171,Nina Vasilyevna Gavrylyuk,F,28.0,167.0,55.0,Russia,RUS,1994,Lillehammer,Cross Country Skiing,Cross Country Skiing Women's 4 x 5 kilometres ...,Gold,winter
24903,41224,Aleksandr Vyacheslavovich Golubyov,M,21.0,174.0,74.0,Russia,RUS,1994,Lillehammer,Speed Skating,Speed Skating Men's 500 metres,Gold,winter
24912,41785,"Yekaterina Aleksandrovna ""Katya"" Gordeyeva (-G...",F,22.0,NaN,NaN,Russia-1,RUS,1994,Lillehammer,Figure Skating,Figure Skating Mixed Pairs,Gold,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270251,127739,Anna Viktorovna Vyakhireva,F,21.0,168.0,63.0,Russia,RUS,2016,Rio de Janeiro,Handball,Handball Women's Handball,Gold,summer
270782,132795,Yana Karapetovna Yegoryan,F,22.0,175.0,64.0,Russia,RUS,2016,Rio de Janeiro,Fencing,"Fencing Women's Sabre, Individual",Gold,summer
270783,132795,Yana Karapetovna Yegoryan,F,22.0,175.0,64.0,Russia,RUS,2016,Rio de Janeiro,Fencing,"Fencing Women's Sabre, Team",Gold,summer
270792,132899,Tatyana Vladimirova Yerokhina,F,31.0,185.0,73.0,Russia,RUS,2016,Rio de Janeiro,Handball,Handball Women's Handball,Gold,summer
271043,134759,Viktoriya Yuryevna Zhilinskayte,F,27.0,188.0,80.0,Russia,RUS,2016,Rio de Janeiro,Handball,Handball Women's Handball,Gold,summer

In [104]:
##OR you could also do
len(russia_gold)

390