# Let's prep our data

### Get the data

- Download to your computer <a href="https://drive.google.com/file/d/1-798fq909hN3x3UxBYUDZrkEaPTliyvJ/view?usp=sharing"> this 256MB file</a> that contains NYPD summons data from 2015-2025s.

In [1]:
## import libraries
import pandas as pd

In [4]:
# import data
df = pd.read_csv("summons-15-25.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384334 entries, 0 to 1384333
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   SUMMONS_KEY            1384334 non-null  int64
 1   SUMMONS_DATE           1384334 non-null  str
 2   OFFENSE_DESCRIPTION    1384316 non-null  str
 3   LAW_SECTION_NUMBER     1348831 non-null  str
 4   LAW_DESCRIPTION        1309406 non-null  str
 5   SUMMONS_CATEGORY_TYPE  1309321 non-null  str
 6   AGE_GROUP              1354372 non-null  str
 7   SEX                    1284382 non-null  str
 8   RACE                   964769 non-null   str
 9   JURISDICTION_CODE      1384334 non-null  int64
 10  BORO                   1372084 non-null  str
 11  PRECINCT_OF_OCCUR      1384334 non-null  int64
 12  X_COORDINATE_CD        1383871 non-null  float64
 13  Y_COORDINATE_CD        1383871 non-null  float64
 14  Latitude               1383870 non-null  float64
 15  Longitude              1383870 non-null  float64
 16  Lon_Lat                1383870 non-null  str
 17  YEAR                   1384334 non-null  int64
dtypes: float64(4), int64(4), str(10)
memory usage: 190.1 MB

## Doesn't AI make learning coding obsolete?

Yes, it's excellent at data analysis and coding. 

But here are a few problems you might run into:

- How will you investigate AI-related topics?
- Hitting Limits – even with paid accounts.
- Protecting sources.
- Not infallibable.

At The Real Deal, Bloomberg and most newsrooms the rule is **you are responsible** for every number, analysis and finding you put into your pieces.

So be prepared to understand and explain each of your decisions, including AI's guidance.

## Traditonal coding v. Vibe Coding

**Traditional coding**
- structured approach to learning syntax and rules first.

**Vibe coding**
- learning by experimenting, observing results, analyzing and iterating – with AI's assistance – rather than memorizing syntax.

- still need to learn coding because you must understand what the code is doing, recognizing mistakes and incorrect interpretations of your prompts.

So you need to retain control of your editorial decisions and process. AI can help write code, but understanding coding helps you trust — or question — the answers.

What are some things - terms, processes etc – that we learned so far?
- Python is good at math
- variables are characters in your data.
- PEMDAS
- f-strings
- built in functions
    - like what? len, type, print, abs, round
- importing and reading data
- understanding dataframes v. series
- getting an overview of your data

# Interviewing Data

If AI can write the code, what questions might you ask based on your domain/beat knowledge?

Let's step back to see how we <a href="https://docs.google.com/presentation/d/1oA50DVvcPT2IWDAHTXogD5lWsWk1TVq_sp5iIS1qQv8/edit?usp=sharing">"interview"</a> data.

## Interviewing Data with AI

### Get the data

- Download <a href="https://drive.google.com/file/d/1-798fq909hN3x3UxBYUDZrkEaPTliyvJ/view?usp=sharing"> this 256MB file</a> to your computer.

### What are some questions you could ask this data?

1. Which borough had the most summons?
2. How many times did the top 10 most common offenses occur?
3. What are the total number of summons broken down by year?
4. What were some of the most unusual summons? (how do you define most unusual)
5. What is the count of summons by gender?
6. How many summons were issued by race?
7. Which borough had the fewest offenses per 100K people?

### Upload data to AI - ask it questions.

#### What happened?

What do we do on deadline when the dataset is too big?

Even if AI ingests a large dataset, it responds by analyzing a fraction of the data.

The importance of <a href="https://docs.google.com/presentation/d/1XbH71D_CyaBnzT30Wa1qn3uM2Jm-XCKkkYACaJ4xmJY/edit?usp=sharing">Reproducible Data Journalism</a>

## And now let's interview data using Pandas

We are soon going to blend using AI and coding, but first it's important to understand some Pandas fundamentals.

#### Importing Data

In [5]:
## read a file
## show how to upload to colab
## import insurance data

summons_df = pd.read_csv("summons-15-25.csv")
summons_df

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384329,140411914,2015-01-01,LITTERING,16-118,Administrative Code,LITTERING,45-64,M,UNKNOWN,0,BROOKLYN,70,995708.0,176233.0,40.650396,-73.958709,POINT (-73.95870942899995 40.65039633400005),2015
1384330,140463604,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BRONX,44,1008656.0,245335.0,40.840038,-73.911797,POINT (-73.91179707599997 40.84003765600005),2015
1384331,140424873,2015-01-01,OTHER ADMIN CODE,9999,Administrative Code,OTHER ADMIN CODE,NaN,D,UNKNOWN,0,MANHATTAN,7,987559.0,201831.0,40.720664,-73.988064,POINT (-73.98806399499993 40.72066379300003),2015
1384332,140418300,2015-01-01,AFTER HOURS CONSUMPTION,106-5,ABC,ABC,45-64,M,UNKNOWN,0,BROOKLYN,67,1003469.0,171347.0,40.636972,-73.930754,POINT (-73.93075448599996 40.63697187500002),2015
1384333,140418234,2015-01-01,DISCON: REFUSE LAWFUL ORDER,240.20-6,Penal Law,DISORDERLY CONDUCT,<18,M,UNKNOWN,0,BRONX,41,1015630.0,236919.0,40.816916,-73.886632,POINT (-73.88663211599999 40.81691612900005),2015

In [7]:
## read the head
summons_df.head()

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024

In [8]:
## show 20 from the top 
summons_df.head(20)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024
5,298704180,2024-12-31,POSS. OF MACE,10-131,Administrative Code,AIR GUN,25-44,F,BLACK,0,STATEN ISLAND,120,962004.0,164939.0,40.619379,-74.080130,POINT (-74.08013 40.619379),2024
6,298702245,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,M,WHITE,0,BROOKLYN,61,996615.0,161248.0,40.609266,-73.955467,POINT (-73.955467 40.609266),2024
7,298697783,2024-12-31,CONSUMPTION OF ALCOHOL IN VEHICLE,1227,VTL,VTL,18-24,M,WHITE HISPANIC,0,BROOKLYN,70,995870.0,175002.0,40.647019,-73.958125,POINT (-73.958125 40.647019),2024
8,298706343,2024-12-31,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),18-24,M,BLACK,0,BRONX,40,1007923.0,237493.0,40.818507,-73.914472,POINT (-73.91447241436298 40.81850733182842),2024
9,298704196,2024-12-31,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),18-24,M,BLACK,0,BROOKLYN,75,1013888.0,179945.0,40.660544,-73.893174,POINT (-73.893174 40.660544),2024
10,298665451,2024-12-31,OPERATION WHILE REGISTRATION OR PRIVILEGE IS S...,512,(null),(null),25-44,F,BLACK,0,BRONX,44,1005852.0,241001.0,40.828142,-73.921942,POINT (-73.9219415 40.8281415),2024
11,298699297,2024-12-31,UNREASONABLE NOISE; FROM CAR MUFFLER/EXHAUST (...,24-236(A),(null),(null),25-44,M,WHITE,0,BROOKLYN,76,982224.0,187792.0,40.682122,-74.007305,POINT (-74.00730471293318 40.682122154525835),2024
12,298672683,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,25-44,F,BLACK,0,BRONX,47,1025287.0,267952.0,40.902044,-73.851552,POINT (-73.85155206210321 40.90204439801025),2024
13,298704456,2024-12-31,POSS. OF KNIFE,10-133,Administrative Code,KNIFE,18-24,M,BLACK HISPANIC,0,MANHATTAN,28,997029.0,230313.0,40.798833,-73.953843,POINT (-73.953843 40.798833),2024
14,298694867,2024-12-31,"PARK DEPARTMENT, JURISDICTION; NOT APPROVED",20-465(J),(null),(null),45-64,M,ASIAN / PACIFIC ISLANDER,0,MANHATTAN,13,987039.0,206948.0,40.734711,-73.989936,POINT (-73.989936 40.734711),2024
15,298730436,2024-12-31,CONSUMPTION OF ALCOHOL IN VEHICLE,1227,VTL,VTL,25-44,M,BLACK,0,BROOKLYN,81,1006703.0,186566.0,40.678729,-73.919050,POINT (-73.91905014945557 40.678728818777344),2024
16,298724975,2024-12-31,DISCON: FIGHTING,240.20-1,Penal Law,DISORDERLY CONDUCT,18-24,M,BLACK,0,MANHATTAN,18,989048.0,218261.0,40.765761,-73.982679,POINT (-73.982679 40.765761),2024
17,298702254,2024-12-31,ACCEPT ON HAIL,19-507,Administrative Code,TLC,65+,M,BLACK,0,QUEENS,103,1037559.0,194576.0,40.700582,-73.807742,POINT (-73.80774181591707 40.70058232906593),2024
18,298711498,2024-12-31,PREVENT CLEAR VIEW INTO LIQUOR STORE,105-10(B),(null),(null),45-64,F,BLACK,0,QUEENS,116,1056865.0,185436.0,40.675367,-73.738214,POINT (-73.738214 40.675367),2024
19,298727975,2024-12-31,RECKLESS DRIVING,1212,VTL,VTL,18-24,M,BLACK,0,BROOKLYN,77,1004888.0,182840.0,40.668506,-73.925605,POINT (-73.9256051783988 40.6685062072618),2024

In [10]:
## read the bottom
summons_df.tail()

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
1384329,140411914,2015-01-01,LITTERING,16-118,Administrative Code,LITTERING,45-64,M,UNKNOWN,0,BROOKLYN,70,995708.0,176233.0,40.650396,-73.958709,POINT (-73.95870942899995 40.65039633400005),2015
1384330,140463604,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BRONX,44,1008656.0,245335.0,40.840038,-73.911797,POINT (-73.91179707599997 40.84003765600005),2015
1384331,140424873,2015-01-01,OTHER ADMIN CODE,9999,Administrative Code,OTHER ADMIN CODE,NaN,D,UNKNOWN,0,MANHATTAN,7,987559.0,201831.0,40.720664,-73.988064,POINT (-73.98806399499993 40.72066379300003),2015
1384332,140418300,2015-01-01,AFTER HOURS CONSUMPTION,106-5,ABC,ABC,45-64,M,UNKNOWN,0,BROOKLYN,67,1003469.0,171347.0,40.636972,-73.930754,POINT (-73.93075448599996 40.63697187500002),2015
1384333,140418234,2015-01-01,DISCON: REFUSE LAWFUL ORDER,240.20-6,Penal Law,DISORDERLY CONDUCT,<18,M,UNKNOWN,0,BRONX,41,1015630.0,236919.0,40.816916,-73.886632,POINT (-73.88663211599999 40.81691612900005),2015

In [11]:
## read bottom 13
summons_df.tail(13)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
1384321,140403875,2015-01-01,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,25-44,M,UNKNOWN,0,BRONX,50,1010971.0,257016.0,40.872092,-73.903384,POINT (-73.903384008 40.872091797000046),2015
1384322,144352156,2015-01-01,FAILURE TO COMPLY WITH SIGN,3-Jan,Park Regs,PARK REGS,25-44,M,NaN,0,BROOKLYN,60,989889.0,148099.0,40.573180,-73.979703,POINT (-73.97970326399997 40.573179905000075),2015
1384323,140394865,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BRONX,48,1016802.0,250581.0,40.854410,-73.882332,POINT (-73.882331632 40.854410101000035),2015
1384324,140394871,2015-01-01,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,18-24,M,UNKNOWN,0,BRONX,46,1011425.0,251298.0,40.856396,-73.901766,POINT (-73.90176562699997 40.85639623900005),2015
1384325,140418242,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,18-24,M,UNKNOWN,0,BRONX,41,1014604.0,238800.0,40.822083,-73.890330,POINT (-73.89033032599998 40.82208252700008),2015
1384326,140403911,2015-01-01,OTHER ABC,9999,ABC,OTHER ABC,25-44,M,UNKNOWN,0,BROOKLYN,67,1002894.0,176689.0,40.651636,-73.932811,POINT (-73.93281147399993 40.65163574300004),2015
1384327,140424899,2015-01-01,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,45-64,M,UNKNOWN,0,BROOKLYN,77,997761.0,186202.0,40.677756,-73.951291,POINT (-73.95129091199995 40.67775613800006),2015
1384328,140411907,2015-01-01,UNLICENSED VEHICLE FOR HIRE,19-506,Administrative Code,TLC,45-64,M,UNKNOWN,0,BROOKLYN,70,995535.0,177158.0,40.652935,-73.959331,POINT (-73.95933133399996 40.652935481000036),2015
1384329,140411914,2015-01-01,LITTERING,16-118,Administrative Code,LITTERING,45-64,M,UNKNOWN,0,BROOKLYN,70,995708.0,176233.0,40.650396,-73.958709,POINT (-73.95870942899995 40.65039633400005),2015
1384330,140463604,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BRONX,44,1008656.0,245335.0,40.840038,-73.911797,POINT (-73.91179707599997 40.84003765600005),2015
1384331,140424873,2015-01-01,OTHER ADMIN CODE,9999,Administrative Code,OTHER ADMIN CODE,NaN,D,UNKNOWN,0,MANHATTAN,7,987559.0,201831.0,40.720664,-73.988064,POINT (-73.98806399499993 40.72066379300003),2015
1384332,140418300,2015-01-01,AFTER HOURS CONSUMPTION,106-5,ABC,ABC,45-64,M,UNKNOWN,0,BROOKLYN,67,1003469.0,171347.0,40.636972,-73.930754,POINT (-73.93075448599996 40.63697187500002),2015
1384333,140418234,2015-01-01,DISCON: REFUSE LAWFUL ORDER,240.20-6,Penal Law,DISORDERLY CONDUCT,<18,M,UNKNOWN,0,BRONX,41,1015630.0,236919.0,40.816916,-73.886632,POINT (-73.88663211599999 40.81691612900005),2015

In [12]:
## get a sample
summons_df.sample()

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
1114894,147765425,2015-11-12,DISCON: UNREASONABLE NOISE,240.20-2,Penal Law,DISORDERLY CONDUCT,45-64,M,NaN,0,BROOKLYN,84,988175.0,190975.0,40.690866,-73.985848,POINT (-73.98584805699994 40.69086637500004),2015

In [13]:
## get sample of 15
summons_df.sample(15)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
604785,311045406,2025-08-08,NON PAYMENT OF FARE (OTHER),1050.4(A),(null),(null),(null),(null),BLACK,1,BROOKLYN,84,988902.0,192641.0,40.695439,-73.983225,POINT (-73.9832253756043 40.6954388081238),2025
1303544,142450885,2015-04-25,DISCON: OBSTRUCT PEDESTRIAN,240.205A,Penal Law,DISORDERLY CONDUCT,18-24,M,NaN,0,BROOKLYN,71,1003358.0,182945.0,40.668806,-73.931122,POINT (-73.93112156699993 40.66880609300006),2015
90851,280743493,2024-01-16,UNREGISTERED VEHICLE,401,VTL,VTL,25-44,M,BLACK,0,BROOKLYN,79,999910.0,192864.0,40.696030,-73.943526,POINT (-73.94352632050453 40.69603000487981),2024
624878,313803987,2025-09-30,OTHER TRANSIT REG,9999,ABC,OTHER ABC,25-44,M,BLACK,1,MANHATTAN,10,984791.0,209846.0,40.742664,-73.998049,POINT (-73.9980491084798 40.7426636084461),2025
693133,168085399,2017-08-08,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,NaN,D,NaN,0,STATEN ISLAND,121,931601.0,158785.0,40.602356,-74.189600,POINT (-74.18960002699998 40.60235624300003),2017
138876,272439419,2023-08-04,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),45-64,M,WHITE HISPANIC,0,QUEENS,110,1022555.0,212540.0,40.749967,-73.861751,POINT (-73.8617511818965 40.749966750834645),2023
333732,213495999,2020-05-25,"MARIJUANA, UNLAWFUL POSSESSION 2ND DEGREE",221.05,Penal Law,MARIJUANA,25-44,M,BLACK HISPANIC,0,BRONX,52,1010695.0,254764.0,40.865912,-73.904391,POINT (-73.90439085 40.86591158),2020
71941,284330022,2024-03-25,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),25-44,F,BLACK,0,STATEN ISLAND,120,962808.0,174275.0,40.644996,-74.077263,POINT (-74.077263 40.644996),2024
549508,301995627,2025-02-24,SMOKING IN TRAIN STATION,1050.7,(null),(null),18-24,M,BLACK,1,BROOKLYN,77,990444.0,188607.0,40.684367,-73.977667,POINT (-73.97766721 40.68436736),2025
707860,166657412,2017-06-26,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,18-24,M,BLACK HISPANIC,0,MANHATTAN,33,1001876.0,246052.0,40.842022,-73.936298,POINT (-73.93629840599993 40.84202174700005),2017
270,298628404,2024-12-30,"SIGNS, UNAUTHORIZED; TAXI, ETC",19-506(C),(null),(null),65+,M,WHITE HISPANIC,0,QUEENS,115,1017959.0,211898.0,40.748223,-73.878342,POINT (-73.87834206982386 40.74822333908418),2024
322813,217349356,2020-09-02,FEDERAL MOTOR VEH. SAFETY REG,NaN,NYS Transportation,NYS TRANS,UNKNOWN,NaN,NaN,0,QUEENS,109,1032051.0,217053.0,40.762316,-73.827448,POINT (-73.827448 40.7623158),2020
208106,254107901,2022-11-14,BICYCLE ON SIDEWALK,19-176,Administrative Code,BIKE,45-64,M,ASIAN / PACIFIC ISLANDER,0,BROOKLYN,73,1008874.0,184510.0,40.673080,-73.911231,POINT (-73.91123055 40.67307979),2022
1010944,152465432,2016-04-22,OTHER HEALTH CODE,9999,Health Code,OTHER HEALTH CODE,25-44,M,NaN,0,MANHATTAN,14,988050.0,214940.0,40.756645,-73.986285,POINT (-73.98628527499993 40.75664455700007),2016
212778,253082450,2022-10-24,UNREASONABLE NOISE; FROM CAR MUFFLER/EXHAUST (...,24-236(A),(null),(null),18-24,M,ASIAN / PACIFIC ISLANDER,0,QUEENS,102,1031642.0,190872.0,40.690451,-73.829107,POINT (-73.829107 40.690451),2022

In [14]:
## get info
summons_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384334 entries, 0 to 1384333
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   SUMMONS_KEY            1384334 non-null  int64
 1   SUMMONS_DATE           1384334 non-null  str
 2   OFFENSE_DESCRIPTION    1384316 non-null  str
 3   LAW_SECTION_NUMBER     1348831 non-null  str
 4   LAW_DESCRIPTION        1309406 non-null  str
 5   SUMMONS_CATEGORY_TYPE  1309321 non-null  str
 6   AGE_GROUP              1354372 non-null  str
 7   SEX                    1284382 non-null  str
 8   RACE                   964769 non-null   str
 9   JURISDICTION_CODE      1384334 non-null  int64
 10  BORO                   1372084 non-null  str
 11  PRECINCT_OF_OCCUR      1384334 non-null  int64
 12  X_COORDINATE_CD        1383871 non-null  float64
 13  Y_COORDINATE_CD        1383871 non-null  float64
 14  Latitude               1383870 non-null  float64
 15  Longitude              1383870 non-null  float64
 16  Lon_Lat                1383870 non-null  str
 17  YEAR                   1384334 non-null  int64
dtypes: float64(4), int64(4), str(10)
memory usage: 190.1 MB

In [16]:
## create a series dot notation
summons_df.OFFENSE_DESCRIPTION

0                        DISORDERLY CONDUCT
1                           IMPROPER PLATES
2                                  TRESPASS
3             FEDERAL MOTOR VEH. SAFETY REG
4          POSSESSION OF ALCOHOL BY A MINOR
                         ...
1384329                           LITTERING
1384330            MARIJUANA, POSSESSION OF
1384331                    OTHER ADMIN CODE
1384332             AFTER HOURS CONSUMPTION
1384333         DISCON: REFUSE LAWFUL ORDER
Name: OFFENSE_DESCRIPTION, Length: 1384334, dtype: str

In [18]:
## create a series square bracket notation
##note -- these show the same thing, but bracket notation is preferred bc dot notation breaks easily. it doesnt work if column names have spaces
##or conflict with pandas commands, or if column names start with numbers

summons_df["OFFENSE_DESCRIPTION"]

0                        DISORDERLY CONDUCT
1                           IMPROPER PLATES
2                                  TRESPASS
3             FEDERAL MOTOR VEH. SAFETY REG
4          POSSESSION OF ALCOHOL BY A MINOR
                         ...
1384329                           LITTERING
1384330            MARIJUANA, POSSESSION OF
1384331                    OTHER ADMIN CODE
1384332             AFTER HOURS CONSUMPTION
1384333         DISCON: REFUSE LAWFUL ORDER
Name: OFFENSE_DESCRIPTION, Length: 1384334, dtype: str

In [20]:
## export a sample to a `csv`
small_sample = summons_df.sample(20)
small_sample.to_csv("my_sample", index = False)

#### Finally **Vibe Coding**!

Recall some questions we want to ask:

1. Which borough had the most summons?
2. How many times did the top 10 most common offenses occur?
3. What are the total number of summons broken down by year?
4. What were some of the most unusual summons? (how do you define most unusual)
5. What is the count of summons by gender?
6. How many summons were issued by race?
7. Which borough had the fewest offenses per 100K people?

##### Template for Vibe Coding

1. Give AI a sample of your data (like a 100 rows)
2. Ask it for the Pandas code to answer a question, **but always tell it to comment the code**!
3. Leave a comment in Markdown with your prompt
4. Test it out in a code cell.
5. If the code throws an error, copy the entire code and give it AI.
6. Remember to add this updated prompt to your markdown.
7. Test out the the updated code in same cell.
8. Create a markdown cell in which you use f-strings to leave your finding

#### 1. Give AI a sample of your data (like a 100 rows)

In [21]:
## see sample data
df.sample(10)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
329467,213983517,2020-06-09,FEDERAL MOTOR VEH. SAFETY REG,NaN,NYS Transportation,NYS TRANS,UNKNOWN,NaN,NaN,0,QUEENS,109,1032051.0,217053.0,40.762316,-73.827448,POINT (-73.827448 40.7623158),2020
1381265,140549223,2015-01-13,OTHER NYS TRANSPORTATION,9999,NYS Transportation,NYS TRANS,NaN,D,UNKNOWN,0,QUEENS,107,1034961.0,195828.0,40.704042,-73.817103,POINT (-73.81710339999995 40.70404229900004),2015
1081985,149236324,2016-01-09,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,<18,M,NaN,2,BRONX,42,1011316.0,240368.0,40.826397,-73.902204,POINT (-73.90220376499997 40.82639692600002),2016
24717,293495170,2024-09-18,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
256124,239942125,2022-02-01,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,72,983296.0,186687.0,40.679089,-74.003439,POINT (-74.00343947 40.67908936),2022
48302,289074351,2024-06-24,SPEED/DRIVING DANGEROUS TO PASSENGER/PEDESTRIA...,2-21(A),(null),(null),18-24,M,WHITE,0,STATEN ISLAND,123,938421.0,131651.0,40.527908,-74.164855,POINT (-74.16485464635048 40.52790847242828),2024
67811,285432235,2024-04-13,UNLAWFUL POSSESSION OF CANNABIS,222.25,(null),(null),18-24,M,BLACK HISPANIC,2,BRONX,45,1033311.0,238482.0,40.821117,-73.822742,POINT (-73.82274170356568 40.82111733337668),2024
966929,153926329,2016-06-11,DISCON: FIGHTING,240.20-1,Penal Law,DISORDERLY CONDUCT,18-24,M,UNKNOWN,0,BRONX,40,1005664.0,234188.0,40.809450,-73.922646,POINT (-73.92264586599998 40.80945007600008),2016
881246,156828246,2016-09-18,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BROOKLYN,75,1017314.0,184900.0,40.674131,-73.880804,POINT (-73.88080390599998 40.67413100800008),2016
930752,155172876,2016-07-21,PICK UP FROM BUS STOP,145-6,Tax Law,TLC,18-24,M,BLACK,0,BROOKLYN,71,1003224.0,181035.0,40.663564,-73.931610,POINT (-73.93160997999998 40.663563856000046),2016

In [22]:
summons_excerpt = df.sample(100)
summons_excerpt.to_csv("summons_samples.csv", index = False)

## Who wants to share their answers?

In [23]:
# 1. Which borough had the most summons? 

boro_counts = df["BORO"].value_counts()
boro_counts

BORO
BROOKLYN         427679
BRONX            312327
MANHATTAN        275884
QUEENS           246314
NEW YORK          63056
STATEN ISLAND     46824
Name: count, dtype: int64

In [24]:
## write as an f-string
# Count summons by borough (sorted highest to lowest automatically)

# Get the top two boroughs
top_two = boro_counts.head(2)

# Extract the name of the borough with the most summons
first_boro = top_two.index[0]

# Extract the number of summons for that borough
first_count = top_two.iloc[0]

# Extract the name of the borough with the second-most summons
second_boro = top_two.index[1]

# Extract the number of summons for that borough
second_count = top_two.iloc[1]

# Create a formatted sentence using f-strings
# :, adds comma formatting to large numbers
# .title() makes borough names title case instead of ALL CAPS
summary = (
    f"{first_boro.title()} issued the most summons "
    f"({first_count:,}), followed by {second_boro.title()} "
    f"with {second_count:,}."
)

# Print the final sentence
print(summary)

Brooklyn issued the most summons (427,679), followed by Bronx with 312,327.

In [25]:
# 2. What were the top 10 most common offenses?
# Get top 10 offenses
top10 = (
    df["OFFENSE_DESCRIPTION"]
    .value_counts()
    .head(10)
)

print(top10)

OFFENSE_DESCRIPTION
CONSUMPTION OF ALCOHOL           248650
FEDERAL MOTOR VEH. SAFETY REG    158420
MARIJUANA, POSSESSION OF          84910
URINATING IN PUBLIC               50340
RECKLESS DRIVING                  44691
ALCOHOLIC BEVERAGE IN PUBLIC      43789
FAILURE TO COMPLY WITH SIGN       42810
TRESPASS                          38595
OTHER ADMIN CODE                  31851
DISORDERLY CONDUCT                20743
Name: count, dtype: int64

In [26]:
# 3. What are the total number of summons broken down by year?
# Convert to datetime
df["year"] = pd.to_datetime(df["SUMMONS_DATE"], errors="coerce")
summons_by_year = (
    df["year"]
    .dt.year
    .value_counts()
    .sort_index()
)

print(summons_by_year)

year
2015    297748
2016    267950
2017    165093
2018     89895
2019     85899
2020     55589
2021     45717
2022     58059
2023    106529
2024     94542
2025    117313
Name: count, dtype: int64

In [28]:
# 4. What were some of the most unusual summons?
pd.set_option("display.max_colwidth", None)
# Add a length column
df["desc_length"] = df["OFFENSE_DESCRIPTION"].str.len()

# Sort by longest descriptions
df.sort_values("desc_length", ascending=False)[
    "OFFENSE_DESCRIPTION"
].head(10)

327382    NO SIGN STATING ""CIGARETTE(TOBACCO PRODUCTS)SALE TO PERSONS UNDER 18 PROHIBITED""
314379    NO SIGN STATING ""CIGARETTE(TOBACCO PRODUCTS)SALE TO PERSONS UNDER 18 PROHIBITED""
518953      CREATES A HAZARDOUS OR PHYSICALLY OFFENSIVE CONDITION WITHOUT A LEGITIMATE PURPO
572767      CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
213633      CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
442721      CREATES A HAZARDOUS OR PHYSICALLY OFFENSIVE CONDITION WITHOUT A LEGITIMATE PURPO
554256      CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
433935      CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
88471       CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
11619       CONGREGATES WITH OTHER PERSONS IN PUBLIC AND REFUSES TO DISPERSE BY LAWFUL POLIC
Name: OFFENSE_DESCRIPTION, dtype: str

In [29]:
df.iloc[20925]

SUMMONS_KEY                                                 294315507
SUMMONS_DATE                                               2024-10-03
OFFENSE_DESCRIPTION                        MOTORCYCLE HELMET REQUIRED
LAW_SECTION_NUMBER                                                381
LAW_DESCRIPTION                                                   VTL
SUMMONS_CATEGORY_TYPE                                             VTL
AGE_GROUP                                                       18-24
SEX                                                                 M
RACE                                                   WHITE HISPANIC
JURISDICTION_CODE                                                   0
BORO                                                            BRONX
PRECINCT_OF_OCCUR                                                  42
X_COORDINATE_CD                                             1010474.0
Y_COORDINATE_CD                                              244694.0
Latitude                                                    40.838265
Longitude                                                  -73.905228
Lon_Lat                  POINT (-73.90522783028261 40.83826480276477)
YEAR                                                             2024
year                                              2024-10-03 00:00:00
desc_length                                                      26.0
Name: 20925, dtype: object

In [30]:
# 5. What is the count of summons by gender?

df["SEX"].value_counts()

SEX
M         1013591
F          130370
(null)     105592
D           29961
U            4868
Name: count, dtype: int64

In [31]:
# 6. How many summons were issued by race?
df["RACE"].value_counts()

RACE
BLACK                             316676
WHITE HISPANIC                    192409
UNKNOWN                           185869
WHITE                              87448
BLACK HISPANIC                     70375
(null)                             54376
ASIAN / PACIFIC ISLANDER           49862
AMERICAN INDIAN/ALASKAN NATIVE      5735
OTHER                               2019
Name: count, dtype: int64

In [32]:
#7. Which borough had the fewest offenses per 100K people?


# summons by borough
borough_counts = df["BORO"].value_counts()

# 2020 Census population
populations = {
    "BROOKLYN": 2736074,
    "QUEENS": 2405464,
    "MANHATTAN": 1694251,
    "BRONX": 1472654,
    "STATEN ISLAND": 495747
}

pop = pd.Series(populations)

# combine + compute rate
per_capita = pd.concat([borough_counts, pop], axis=1)
per_capita.columns = ["summons_count", "population"]

per_capita["summons_per_100k"] = (
    per_capita["summons_count"] / per_capita["population"] * 100000
)

per_capita.sort_values("summons_per_100k")

               summons_count  population  summons_per_100k
STATEN ISLAND          46824    495747.0       9445.140364
QUEENS                246314   2405464.0      10239.770789
BROOKLYN              427679   2736074.0      15631.119626
MANHATTAN             275884   1694251.0      16283.537681
BRONX                 312327   1472654.0      21208.444074
NEW YORK               63056         NaN               NaN